version: '3'
services:

  wakeup:
    build: 
      context: ./
      dockerfile: wakeup-server/Dockerfile
    container_name: wakeup
    ports:
      - 5001:5001
    env_file:
      - wakeup-server/.env.compose

