name: Build for Release 

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # Caching pip dependencies

      - name: Install linux dependencies
        run: sudo apt-get install libasound2-dev libasound2 portaudio19-dev python3-pyaudio -y

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Run build script
        run: ./scripts/run_build_all.sh

      - name: Create release artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release ${{ github.event.inputs.tag }}
          path: ./dist

      - name: Create release tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        if: success()
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            Release ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
