name: Docker Health Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
    


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up local env
        run: ./scripts/setup_local_env.sh -o -d

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip3 install -r wakeup_server/requirements.txt && cd zeromq && pip install . && cd ..
      
      - name: Run pytest
        run:  cd wakeup_server && pytest

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker container
        run: docker-compose up -d

      - name: Run tests inside container
        run: docker exec wakeup_server pytest